# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
orbs:
  node: circleci/node@4.7
  python: circleci/python@2.0.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:17.5.0
    steps:
      - checkout
      - run:
          command: "sudo ln -s /usr/bin/python3 /usr/bin/python"
      - run:
          command: "export PYTHONPATH=/usr/bin/"
      - run: npm install
      - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
