# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
orbs:
  node: circleci/node@4.7
  python: circleci/python@2.0.0

jobs:
  build_and_test:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install
          name: Install pkgs
      - run:
          command: "sudo ln -s /usr/bin/python3 /usr/bin/python"
      - node/test:
          version: '16.10'
          pkg-manager: npm

workflows:
  jobs:
    - build_and_test          
